version: "3.7"

services:
  rails:
    build: .
    restart: unless-stopped
    environment:
      - RAILS_ENV=development
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=postgres

    ports:
      - "3001:3000"

    volumes:
      - .:/app
    networks:
      - matias-network
    # depends_on:
    #   - postgres
    command: ["sh", "-c", "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    # This is needed to allow the rails server dont reboot with a debugger method attached
    stdin_open: true
    tty: true
  postgres:
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=matias_development
    networks:
      - matias-network
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  matias-network:
    driver: bridge
