default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 5 } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 5 } %>

development:
  <<: *default
  database: sptools_development
  username: <%= ENV.fetch("DATABASE_USERNAME") { 5 } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 5 } %>

test:
  <<: *default
  database: sptools_test

production:
  <<: *default
  database: sptools_production
  username: <%= ENV.fetch("DATABASE_USERNAME") { 5 } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 5 } %>
