# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <% ENV.fetch("DATABASE_HOST") %>

development:
  <<: *default
  database: matias_development
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: 'postgres'

test:
  <<: *default
  database: matias_test

production:
  <<: *default
  database: matias_production
  username: your_production_username
  password: <%= ENV['YOUR_PROJECT_DATABASE_PASSWORD'] %>
